name: publish_tag

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_tag:
    name: cargo publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_LOGIN }}
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run --manifest-path ./netstack/Cargo.toml
